server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/rmt
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
